- name: Install utilities
  yum:
    name: "{{ item }}"
  with_items:
    - tree
    - tmux

- name: Add /opt/bin to PATH
  copy:
    src: opt.sh
    dest: /etc/profile.d/
    mode: "755"

- name: Enable SELinux
  selinux:
     policy: targeted
     state: enforcing

- import_tasks: httpd.yml
  when: local_test_vm_install_httpd
